- name: Update repositories
  shell: >
    sudo sh -c 'echo "deb [arch=amd64] https://apt-mo.trafficmanager.net/repos/dotnet-release/ xenial main" > /etc/apt/sources.list.d/dotnetdev.list'

- name: Update key
  shell: sudo apt-key adv --keyserver apt-mo.trafficmanager.net --recv-keys 417A0893

- name: Update cache
  apt: update_chache=yes